export const SET_MAIN_DATA = "SET_MAIN_DATA";
export const SET_TOP_SELLING_COURSES = "SET_TOP_SELLING_COURSES";
export const COURSE_FAVOURITE = "ADD_COURSE_TO_FAVOURITE";
export const SET_MY_COURSES = "SET_MY_COURSES";



